name: CMake CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++

      - name: Configure Debug
        run: cmake -S . -B build_debug -DCMAKE_BUILD_TYPE=Debug

      - name: Build Debug
        run: cmake --build build_debug

      - name: Configure Release
        run: cmake -S . -B build_release -DCMAKE_BUILD_TYPE=Release

      - name: Build Release
        run: cmake --build build_release

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++

      - name: Configure Debug
        run: cmake -S . -B build_debug -DCMAKE_BUILD_TYPE=Debug

      - name: Build Debug
        run: cmake --build build_debug

      - name: Run tests
        run: ctest --test-dir build_debug --output-on-failure
